## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("../WeatherPy_vacation.csv")
vacation_df

,Unnamed: 0,Unnamed: 0.1,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Hotel Name
0,0,8,Shakawe,BW,-18.3667,21.8500,67.57,86,80,1.21,Divava Okavango Lodge & Spa
1,1,10,Cairo,EG,30.0626,31.2497,54.36,76,0,2.30,"Marriott Mena House, Cairo"
2,2,13,Port Alfred,ZA,-33.5906,26.8910,68.83,90,58,15.21,Oceana Beach and Wildlife Reserve
3,3,17,Lebu,CL,-37.6167,-73.6500,57.61,91,98,5.28,Albergo Italiano
4,4,19,Port Elizabeth,ZA,-33.9180,25.5701,66.49,94,100,10.36,"Radisson Blu Hotel, Port Elizabeth"
...,...,...,...,...,...,...,...,...,...,...,...
145,145,663,Tonk,IN,26.1667,75.7833,56.08,40,0,4.34,Six Senses Fort Barwara
146,146,664,Eureka,US,40.8021,-124.1637,60.75,90,100,1.01,Best Western Plus Humboldt Bay Inn
147,147,666,Valparaíso,CL,-33.0393,-71.6273,66.47,77,75,5.75,Hotel Boutique 17
148,148,669,Ponta Delgada,PT,37.7333,-25.6667,58.50,62,75,4.61,VIP Executive Azores Hotel
149,149,674,Thaba-Tseka,LS,-29.5220,28.6084,55.38,84,67,1.70,Mohale Oa Masite Hotel

In [3]:
my_itinerary = vacation_df[vacation_df["Country"] == "US"]

my_itinerary.reset_index(drop=True,inplace=True)
my_itinerary

,Unnamed: 0,Unnamed: 0.1,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Hotel Name
0,7,38,San Patricio,US,28.0170,-97.5169,55.49,39,92,8.39,Hampton Inn & Suites Corpus Christi
1,14,75,Saint George,US,37.1041,-113.5841,61.36,17,0,0.63,Sleep Inn & Suites Hurricane Zion Park Area
2,25,144,Del Rio,US,29.3627,-100.8968,56.23,27,0,9.73,Quality Inn & Suites Del Rio
3,38,200,Fortuna,US,40.5982,-124.1573,62.47,94,100,0.00,Best Western Plus Humboldt Bay Inn
4,42,214,Portland,US,45.5234,-122.6762,58.42,62,0,7.00,The Society Hotel - Portland
5,55,259,Laguna,US,38.4210,-121.4238,68.18,49,0,3.44,Hampton Inn & Suites Sacramento-Cal Expo
6,109,503,North Bend,US,43.4065,-124.2243,51.24,95,100,7.27,Sunset Oceanfront Lodging
7,141,643,Bernalillo,US,35.0500,-106.6673,52.16,24,0,4.61,Comfort Inn & Suites
8,142,650,Socorro,US,31.6546,-106.3033,57.18,29,0,0.76,Holiday Inn Express & Suites Cd. Juarez - Las ...
9,146,664,Eureka,US,40.8021,-124.1637,60.75,90,100,1.01,Best Western Plus Humboldt Bay Inn

In [4]:
city_1 = (my_itinerary.loc[0]["Lat"],my_itinerary.loc[0]["Lng"])
city_2 = (my_itinerary.loc[1]["Lat"],my_itinerary.loc[1]["Lng"])
city_3 = (my_itinerary.loc[2]["Lat"],my_itinerary.loc[2]["Lng"])
city_4 = (my_itinerary.loc[3]["Lat"],my_itinerary.loc[3]["Lng"])

chosen_itinerary_df = my_itinerary[(my_itinerary["City"] == "San Patricio") | (my_itinerary["City"] == "Saint George") | (my_itinerary["City"] == "Del Rio") | (my_itinerary["City"] == "Fortuna")]  
chosen_itinerary_df

,Unnamed: 0,Unnamed: 0.1,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Hotel Name
0,7,38,San Patricio,US,28.0170,-97.5169,55.49,39,92,8.39,Hampton Inn & Suites Corpus Christi
1,14,75,Saint George,US,37.1041,-113.5841,61.36,17,0,0.63,Sleep Inn & Suites Hurricane Zion Park Area
2,25,144,Del Rio,US,29.3627,-100.8968,56.23,27,0,9.73,Quality Inn & Suites Del Rio
3,38,200,Fortuna,US,40.5982,-124.1573,62.47,94,100,0.00,Best Western Plus Humboldt Bay Inn

In [5]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc["Del Rio"]
vacation_end = vacation_df.loc["Del Rio"]
vacation_stop1 = vacation_df.loc["Fortuna"]
vacation_stop2 = vacation_df.loc["Saint George"] 
vacation_stop3 = vacation_df.loc["Fortuna"]

KeyError: 'Del Rio'

In [ ]:
selectedItenary_df = my_itenary[(my_itenary["City"] == "Malacacheta") | (my_itenary["City"] == "Rio Verde De Mato Grosso") | (my_itenary["City"] == "Jatai") | (my_itenary["City"] == "Jales")]  
# selectedItenary_df.append(my_itenary.loc[4:6])
selectedItenary_df

In [ ]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([],ignore_index=True)
itinerary_df

In [ ]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """

"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [ ]:
# 11a. Add a marker layer for each city to the map.

# 11b. Display the figure